apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning
  labels:
    app: learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learning
  template:
    metadata:
      labels:
        app: learning
    spec:
      containers:
        - name: learning_container
          image: 747483667782.dkr.ecr.us-east-2.amazonaws.com/project_learning:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
